### PR TITLE
Sort By Drodown visible in both versions now

### PR DESCRIPTION
**Pull request by Vishalk91-4**
Fixes issue #40 

There are no error in console, sort by is now visible in both mobile and desktop, isn't causing conflicts 

@llaske could you please review it
Screenshot 2023-09-30 092609
image

### CODE REVIEW

**Comment by llaske** [comment]
Hmmm. Having a "SORT BY" text in the middle of the screen is ugly for a low benefit since sorting is not a major feature.
Plus the text is not localized.
The small arrow in the original version was better.

image

**Comment by Vishalk91-4** [comment]
@llaske, made changes according to the arrow one, you said
Could you please review it


https://github.com/llaske/sugarizer-doc/assets/116670999/114c1728-1cd8-4660-9ea8-18c35afc00ba

**Comment by llaske** [comment]
@Vishalk91-4 that's better.

Is it possible to hide the "Sort by" combo on the mobile version?

image

**Comment by Vishalk91-4** [comment]
@llaske 

Removed that from Mobile Screen

image

Could you please review this PR

**Review by llaske — COMMENTED** [review]
Nice. Thanks.

**Pull request merged**
