### PR TITLE
X Logo update

### PR DESCRIPTION
**Pull request by HitanshuPrasad**
Updated X (twitter logo) by creating one using Glyph and CSS for issue #46 
Screenshot from 2023-12-22 23-14-45

### CODE REVIEW

**Comment by llaske** [comment]
The icon size and alignment is wrong.

**Comment by HitanshuPrasad** [comment]
I have updated the font awesome files to v 6.5.1 (latest available for download ) . Please review the PR again. This has in sense updated the discord and X logo to the latest .

**Comment by llaske** [comment]
The Discord icon should be boxed and align with other icons.

image

**Comment by HitanshuPrasad** [comment]
The latest version of font-awesome icons seems to only have this discord icon and not boxed one. Any suggestion hwo should i proceed now ? Updating to older version would revert back the X icon.

**Comment by llaske** [comment]
> Any suggestion hwo should i proceed now ?

I see two solutions: 
* try to adapt the Discord component in the new version to surround it with a box
* reverse back to the old version and try to retrieve the X logo in another way.

**Pull request closed without merging**
