### PR TITLE
Enabled Dropdown in Activities

### PR DESCRIPTION
**Pull request by Vishalk91-4**
Fixes issue #38

Dropdown is completely working and the previous and next also respond

https://github.com/llaske/sugarizer-doc/assets/116670999/5a7332e8-f4e1-4b53-943b-e4ef23b17b03

@llaske could you please review it

### CODE REVIEW

**Comment by llaske** [comment]
The default seems to be 5, it should be All.

**Comment by Vishalk91-4** [comment]
> The default seems to be 5, it should be All.

@llaske, I'll change that, I thought that in desktop we can view like 57 activities, but it would become difficult in smaller versions, so I did 5

**Comment by Vishalk91-4** [comment]
@llaske, changed it to All.

**Comment by llaske** [comment]
Nice. Thanks.

**Pull request merged**
