### PR TITLE
Article Typo and Copyright Fix

### PR DESCRIPTION
**Pull request by Vishalk91-4**
Fixes issue #51 and #52 

Fixed Copyright by adding script code
@llaske, I saw that it is written not to update the article files, I have just changed the footer, no content

Fixed Typo in Article

Screenshot 2023-12-26 083804
Screenshot 2023-12-26 083741
@llaske, could you please review it

### CODE REVIEW

**Review by samyakshah3008 — CHANGES_REQUESTED** [review]
Hey man, nice work. But to make this production ready code, I have a small potential suggestion: 

Instead of writing 
`<script>
	document.getElementById('currentYear').textContent = new Date().getFullYear();
</script>` in each of the html file, can't we have one single helper.js file where we can define this function? And use it everywhere we want? (following the DRY approach -- don't repeat yourself) 

Think of it like in future sugarizer is having 500html files, and writing this same logic 500times is not feasible solution. 

Potential change you can make for production ready code: 

Make a helper.js file and in which write the logic: 

`const getCurrentYear = () => new Date().getFullYear()
document.getElementById('currentYear').innerText = getCurrentYear();`

Html file where you want `currentYear` value: 

Attach `<script src="../../js/helper.js"></script>
` at the bottom of html file  and the html code will be: `2013-<span id="currentYear"></span>`

**Comment by Vishalk91-4** [comment]
> Hey man, nice work. But to make this production ready code, I have a small potential suggestion:
> 
> Instead of writing `<script> document.getElementById('currentYear').textContent = new Date().getFullYear(); </script>` in each of the html file, can't we have one single helper.js file where we can define this function? And use it everywhere we want? (following the DRY approach -- don't repeat yourself)
> 
> Think of it like in future sugarizer is having 500html files, and writing this same logic 500times is not feasible solution.
> 
> Potential change you can make for production ready code:
> 
> Make a helper.js file and in which write the logic:
> 
> `const getCurrentYear = () => new Date().getFullYear() document.getElementById('currentYear').innerText = getCurrentYear();`
> 
> Html file where you want `currentYear` value:
> 
> Attach `<script src="../../js/helper.js"></script> ` at the bottom of html file and the html code will be: `2013-<span id="currentYear"></span>`

I thought of it at the start, but then it leads to increased no. of HTTP requests and may increase the load time especially for mobile, so I didn't consider it and 
I don't think there are going to be that many files for articles on sugarizer.org, if it had to be for try.sugarizer.org then I would have implemented it

@llaske I'll add whatever you fell is the best

**Comment by samyakshah3008** [comment]
Cool, nice catch Vishal. 
But that won't be some drastic load time is what I feel, repeating same code at more than 17 files is not seem to be good in my opinion.

**Comment by samyakshah3008** [comment]
In this PR you have made this changes where the year was 2022 and 2023, 
please make changes across the project too where year timeline is present, because we are now moving towards dynamic. @Vishalk91-4 

You can use VSCode search feature

**Comment by Vishalk91-4** [comment]
> Cool, nice catch Vishal. But that won't be some drastic load time is what I feel, repeating same code at more than 17 files is not seem to be good in my opinion.

I guess we will let @llaske, find which one is feasible and that will be implemented
I believe all timeline changes related to this repo have been implemented, FYI.

**Comment by llaske** [comment]
In copyright law only the year of first publication of the work is need, so it's not a requirement to change it each year.
Plus, as a comment mention in the beginning of all HTML files, articles are generated from the MD files using header and footer in `scripts/templates` so it has no sense to update articles.

**Comment by Vishalk91-4** [comment]
> In copyright law only the year of first publication of the work is need, so it's not a requirement to change it each year. Plus, as a comment mention in the beginning of all HTML files, articles are generated from the MD files using header and footer in `scripts/templates` so it has no sense to update articles.

Sure @llaske, would keep that in mind
Now this PR only changes, 

- the initial copyright of page
- Article Typo

**Review by samyakshah3008 — APPROVED** [review]
Good work

**Comment by llaske** [comment]
Cool. Thanks @Vishalk91-4

**Pull request merged**
