### PR TITLE
Automatic choice of proper index basing on browser's language

### PR DESCRIPTION
**Pull request by tradzik**
Simple JavaScript implementation. If the requested language is not available, the English version is being displayed.

### CODE REVIEW

**Comment by piotrantosz** [comment]
Works for me on chrome and firefox.

**Comment by tradzik** [comment]
Should be closed if #14 is merged.

**Comment by piotrantosz** [comment]
I didn't supposed that second task "gonna be made" / "gonna be made so quickly". Good job, tho.

**Comment by llaske** [comment]
Cool. Thanks.

**Pull request merged**
