### PR TITLE
Changes to language of site main page

### PR DESCRIPTION
**Pull request by joshuaalm**
I have edited the language on the site to clarify the purpose of Sugarizer.  Please feel free to accept or reject individually any of the changes as you see fit to do so.  I did not know how to refresh the contents of index.html from the configuration files, but I noticed the *.po files and locale.ini, and I will happily copy the changes over manually or run whatever command will generate the correct result, and then create a new PR.

### CODE REVIEW

**Comment by llaske** [comment]
Thanks for your contribution.
Two things:
- Avoid include in your PR settings local to your environment (`.vscode/settings.json`)
- Localization for this site should be done on https://translate.sugarizer.org/projects/sugarizer/sugarizer-website/

**Comment by joshuaalm** [comment]
Thank you for the advice.  I will try to remember to add .vscode to .gitignore for projects from now on.  I have registered for the translation site, and I am waiting for my confirmation email.

**Comment by joshuaalm** [comment]
@llaske I registered on the Weblate site, but haven't received a verification email.  Is that something you have to approve?

**Comment by llaske** [comment]
Hmmm. Strange. Could you tell me the mail address and login you've used?

**Comment by joshuaalm** [comment]
My address is a gmail account with the same handle as on here.

**Comment by llaske** [comment]
You're right, look like somethings goes wrong with user creation.
I've created your account manually and sent you connection information.

**Comment by joshuaalm** [comment]
Thank you!.  I was able to log in with that information.  I've made the
changes to the translation.

**Comment by llaske** [comment]
Seen. Thanks.

**Pull request closed without merging**
