### PR TITLE
Updated All logos (socials + apps)

### PR DESCRIPTION
**Pull request by Vishalk91-4**
Fixes issue #46

Screenshot 2024-01-02 175958
Screenshot 2024-01-02 180016

@llaske, updated all logos to latest, please review it

### CODE REVIEW

**Comment by llaske** [comment]
Could you fix the conflicting files?

**Comment by Vishalk91-4** [comment]
@llaske, fixed the conflicting files

**Comment by Vishalk91-4** [comment]
> Could you fix the conflicting files?

@llaske, fixed all conflicting files

**Comment by llaske** [comment]
It seems you've duplicated the footer.

image

**Comment by Vishalk91-4** [comment]
@llaske, I guess when previous commits were added, it got overlapped
Changed it now

**Review by llaske — COMMENTED** [review]
Nice. Thanks

**Pull request merged**
